version: '2'
services:
    oplusdts-app:
        image: oplusdts
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oplusdts-mysql:3306/oplusdts?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    oplusdts-mysql:
        extends:
            file: mysql.yml
            service: oplusdts-mysql
